export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const SHOW_SNACKBAR = "SHOW_SNACKBAR"
export const DONE_TODO = "DONE_TODO"
export const IS_EDITING = "IS_EDITING"
export const EDIT_TODO = "EDIT_TODO"